#!/usr/bin/env python3
import os
import sys

def RemoteGoldenDir():
    return "none"

def get_cmake_filename():
    return "CMakeTestAutoGeneration.cmake"
def get_test_db_filename():
    return "test_definition.txt"

def cmake_code_block(args, label):
    name = args.replace(" ", "_")
    s = '''
add_test(NAME "%s" COMMAND bash -c "PYTHONPATH=${CMAKE_BINARY_DIR}/src %s")
set_tests_properties("%s" PROPERTIES LABELS "%s")
    ''' %(name, args, name, label)
    return s
def get_cmake_info():
    return '''
###################################################
# this(%s) is automatically generated by '%s'. 
# The behavior of modifying this file is undefined.
###################################################
message(STATUS "load ctests automatic generated success")
''' %(get_cmake_filename(), os.path.basename(__file__))

aligin = 20
def generate_cmake():
    print("* Welcome to ctest automatic generation module")
    print("    - pwd".ljust(aligin), os.getcwd())
    print("    - output".ljust(aligin), get_cmake_filename())
    print("    - test database".ljust(aligin), get_test_db_filename())

    with open(get_test_db_filename(), 'r') as file:
        lines = file.readlines()

    with open(get_cmake_filename(), 'w') as file:
        file.write(get_cmake_info())
        for i in range(0, len(lines), 2):
            args = lines[i].strip() 
            labels = lines[i + 1].strip()
            file.write(cmake_code_block(args, labels))
def init_ctest_env():
    dest = sys.argv[1]
    remote = RemoteGoldenDir()
    print("* Welcome to the ctest initialization module")
    print("    - destination".ljust(aligin), dest)
    print("    - golden dir".ljust(aligin), remote)

    
    def download_with_message(proj, resource):
        print(f"    - downloading test resource of {proj}...")
        for r in resource:
            cmd = f"rsync -a -q {remote}/{proj}/{r} {dest}"
            assert(0 == os.system(cmd))
            print(f"    - downloaded {r} to {dest}")
    if "none" == remote: return
    download_with_message("rcwa_tests", ["sourcedata"])

print("\n")    
generate_cmake()
init_ctest_env()